### ISSUE TITLE
KoNLP 라이브러리 설치지 bit64라고 불리는 패키지가 없다고 뜹니다.

### ISSUE THREAD

**Issue by J-Rigondo** [youngwoos/Doit_R#19]
안녕하세요

Error: package or namespace load failed for ‘KoNLP’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 ‘bit64’이라고 불리는 패키지가 없습니다

이런 에러가 뜹니다.
저는 현재 이클립스로 자바도 쓰고 있고 R이나 자바나 전부 64비트로 같다는 것을 확인했습니다.
위와 같은 에러가 왜뜨는지 모르겠습니다ㅜ

**Comment by youngwoos** [comment]
안녕하세요? `bit64` 패키지를 설치한 후에 `KoNLP` 패키지를 설치해보시겠어요?
