### ISSUE TITLE
KoNLP 에러문제..

### ISSUE THREAD

**Issue by bbunsuni** [youngwoos/Doit_R#29]
1. 에러 해결에 관한 카페글대로 실행하였는데 마지막에 이런 에러메세지가 뜹니다.

Error: package or namespace load failed for 'KoNLP':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: 공유된 객체 'C:/R/R-3.6.1/library/rJava/libs/i386/rJava.dll'를 로드 할 수 없습니다:
  LoadLibrary failure:  %1은(는) 올바른 Win32 응용 프로그램이 아닙니다.

에러: 로딩에 실패했습니다
실행이 정지되었습니다
*** arch - x64
URL 'http://central.maven.org/maven2/org/scala-lang/scala-library/2.11.8/scala-library-2.11.8.jar'을 시도합니다
unable to resolve 'central.maven.org'URL 'http://downloads.lightbend.com/scala/2.11.8/scala-2.11.8.zip'을 시도합니다
Content type 'application/zip' length 28729349 bytes (27.4 MB)
==================================================
downloaded 27.4 MB

Successfully installed Scala runtime library in C:/R/R-3.6.1/library/00LOCK-KoNLP/00new/KoNLP/java/scala-library-2.11.8.jar
ERROR: loading failed for 'i386'
* removing 'C:/R/R-3.6.1/library/KoNLP'
Error: Failed to install 'KoNLP' from GitHub:
  (converted from warning) installation of package ‘C:/Users/HOME/AppData/Local/Temp/RtmpYNgSbr/file334c19a65830/KoNLP_0.80.2.tar.gz’ had non-zero exit status

2. 혹시 KoNLP_0.80.2.tar.gz 이런 파일을 다운받았는데 설치할 수 있나요?

**Comment by youngwoos** [comment]
에러 메시지를 보니 java를 찾지 못하는듯 하네요. 아래 링크의 전체 코드를 순서대로 실행해보시겠어요? 앞 부분에 java와 rJava를 설치하는 부분이 있습니다.

https://facebook.com/notes/r-korea-krugkorean-r-user-group/konlp-설치-이슈-공유/1847510068715020/

만약 그래도 오류가 발생하면 데이터 분석 커뮤니티에 올려주세요.

데이터 분석 커뮤니티
https://www.facebook.com/groups/datacommunity/
