### ISSUE TITLE
ggiraphExtra mac 인스톨 문제 

### ISSUE THREAD

**Issue by KUSYSY** [youngwoos/Doit_R#32]
안녕하세요 Mac을 사용중에 ggiraphExtra패키지 인스톨에서 계속 문제가 생겨 질문드립니다. FAQ에 올려주신 링크 따라서 XQuartz설치후에 재부팅했는데 계속 에러가 납니다 ㅜㅜ 
이전에 devtools를 설치할때도 ERROR: configuration failed for package 이런 에러가 났었습니다. (이는 terminal에서 바로 패키지 설치를 했습니다만 ggiraph애들은 웹서핑을 해도 터미널로 인스톨 하는 방법을 못찾겠더라구요...)

나오는 내용은 이렇습니다. 
* installing *source* package ‘systemfonts’ ...
** package ‘systemfonts’ successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=
Using PKG_LIBS=-lfreetype
<stdin>:1:10: fatal error: 'ft2build.h' file not found
#include <ft2build.h>
         ^~~~~~~~~~~~
1 error generated.
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because freetype2 was not found. Try installing:
 * deb: libfontconfig1-dev (Debian, Ubuntu, etc)
 * rpm: fontconfig-devel (Fedora, EPEL)
 * csw: fontconfig_dev (Solaris)
 * brew: freetype (OSX)
If freetype2 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a freetype2.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘systemfonts’
* removing ‘/Users/GabrielSYKim/opt/anaconda3/lib/R/library/systemfonts’
Warning in install.packages :
  installation of package ‘systemfonts’ had non-zero exit status
* installing *source* package ‘zip’ ...
** package ‘zip’ successfully unpacked and MD5 sums checked
** using staged installation
** libs

(brew도 패키지 인스톨로 깔았습니다)
해결을 위해 제가 해본 것은 xcode를 깔고 command tools를 설치해봤던 것과 
terminal에 xcode -select --install 을 하며 gcc 설치를 확인해봤습니다. 
하지만 이후에도 패키지 설치에서 저런 문제가 발생하고 있습니다 ㅜㅜ
며칠째 패키지 설치에 막혀있어 도움이 필요합니다. 감사합니다.

**Comment by skysign** [comment]
제가 맥유저가 아니라서, 정확한 답변은 아닐 수 있습니다.

에러 메세지로보면, systemfonts 패키지를 소스에서 부터, 빌드(컴파일)해서 설치하려고 하는대,
"ft2build.h' 라는 헤더 파일이 없어서, 컴파일을 못해서 생긴 에러 입니다.
검색을 좀 해보니, 해당 헤더 파일은 freetype2 에 속해있는 헤더 파일중에 하나 인 것 같습니다.

맥이라 제가 정확히는 모르겠지만, 리눅스랑 비슷할 것 같아서 답글 남겨 봅니다.

리눅스에서는 보통 한 패키지가 2개 있습니다.
하나는 사용하는 용도고, 다른 하나는 이 패키지를 사용해서 빌드 하는 용도 입니다.
빌드하는 용도의 패키지는 보통 패키지이름의 뒷부분에 -dev 를 붙여 주고,
헤더파일밑 디버깅에 필요한 파일들이 함께 들어 있습니다.

PKG_LIBS=-lfreetype
이 옵션을 봐서는 freetype 패키지를 사용해서 빌드 하는건 맞는 것 같구요,
따라서, freetype의 dev 패키지를 설치하고, 다시 ggiraphExtra 설치하면, 설치가 될 것 같습니다.

검색을 좀 해봤는대요, 아래 사이트를 참고하면, 아마도 아래 커맨드로 해결 될 수 도 있을 것 같습니다.
참고한 사이트 : https://matplotlib.org/3.1.0/users/installing.html

brew install libpng freetype pkg-config

ps : 우연히 gmail을 열었다가, 메일이 와있길래, 잘 모르는 맥이지만, 검색해서 답변 드렸습니다.

ps ps : 책에 직접적으로 관련된 질문 내용이 아니라서, 여기에 올리시기 보다는 다른 R 커뮤니티에 올리시면, 더 빨리 답을 얻을 수 있을 것 같아요.

**Comment by KUSYSY** [comment]
감사합니다!

**Comment by youngwoos** [comment]
@skysign 제가 잘 모르는 분야인데 친절하게 설명해주셔서 감사합니다! 👍

**Comment by youngwoos** [comment]
@KUSYSY 해결 안되시면 `ggiraphExtra` 패키지 저장소에 이슈 남겨보시겠어요? 패키지 개발자 문건웅님이 맥 유저라서 해결 방법을 알고 계실지도 모르겠습니다.
https://github.com/cardiomoon/ggiraphExtra

**Comment by skysign** [comment]
@KUSYSY 어떻게 해결은 되셨어요?

해결 되셨거나, 다른 커뮤니티에서 해결방법을 찾으 시는 중이시면,
이 issue는close 해주시겠어요?
