### ISSUE TITLE
useNIADic() 설치중 오류 (도움 부탁드립니다)

### ISSUE THREAD

**Issue by haloaa** [youngwoos/Doit_R#33]
아래와 같이 계속 오류가 나옵니다. 어떻게 해야하는지 질문드립니다. 

Failed to install 'unknown package' from URL:
  (converted from warning) cannot remove prior installation of package ‘vctrs’Downloading package from url: https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz

=============================================================
> useNIADic()
Backup was just finished!
Downloading package from url: https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                              
 2: CRAN packages only               
 3: None                             
 4: ggplot2   (3.2.1 -> 3.3.0) [CRAN]
 5: vctrs     (0.2.3 -> 0.2.4) [CRAN]
 6: glue      (1.3.1 -> 1.3.2) [CRAN]
 7: Rcpp      (1.0.3 -> 1.0.4) [CRAN]
 8: callr     (3.4.2 -> 3.4.3) [CRAN]
 9: lifecycle (0.1.0 -> 0.2.0) [CRAN]
10: tibble    (2.1.3 -> 3.0.0) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
ggplot2   (3.2.1 -> 3.3.0) [CRAN]
vctrs     (0.2.3 -> 0.2.4) [CRAN]
glue      (1.3.1 -> 1.3.2) [CRAN]
Rcpp      (1.0.3 -> 1.0.4) [CRAN]
callr     (3.4.2 -> 3.4.3) [CRAN]
lifecycle (0.1.0 -> 0.2.0) [CRAN]
isoband   (NA    -> 0.2.0) [CRAN]
tibble    (2.1.3 -> 3.0.0) [CRAN]
Installing 8 packages: ggplot2, vctrs, glue, Rcpp, callr, lifecycle, isoband, tibble
Installing packages into ‘C:/Users/minsoo/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions are later:
       binary source needs_compilation
callr   3.4.2  3.4.3             FALSE
tibble  2.1.3  3.0.0              TRUE

URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/ggplot2_3.3.0.zip'을 시도합니다
Content type 'application/zip' length 4021218 bytes (3.8 MB)
downloaded 3.8 MB

URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/vctrs_0.2.4.zip'을 시도합니다
Content type 'application/zip' length 1027166 bytes (1003 KB)
downloaded 1003 KB

URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/glue_1.3.2.zip'을 시도합니다
Content type 'application/zip' length 153948 bytes (150 KB)
downloaded 150 KB

URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/Rcpp_1.0.4.zip'을 시도합니다
Content type 'application/zip' length 3027979 bytes (2.9 MB)
downloaded 2.9 MB

URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/lifecycle_0.2.0.zip'을 시도합니다
Content type 'application/zip' length 101598 bytes (99 KB)
downloaded 99 KB

URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/isoband_0.2.0.zip'을 시도합니다
Content type 'application/zip' length 2902734 bytes (2.8 MB)
downloaded 2.8 MB

URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/tibble_2.1.3.zip'을 시도합니다
Content type 'application/zip' length 337382 bytes (329 KB)
downloaded 329 KB

package ‘ggplot2’ successfully unpacked and MD5 sums checked
package ‘vctrs’ successfully unpacked and MD5 sums checked

Failed to install 'unknown package' from URL:
  (converted from warning) cannot remove prior installation of package ‘vctrs’Downloading package from url: https://github.com/haven-jeon/NIADic/releases/download/0.0.1/NIADic_0.0.1.tar.gz

**Comment by youngwoos** [comment]
아래 내용 참고해서 `KoNLP`를 다시 설치해보시겠어요?
https://github.com/youngwoos/Doit_R/blob/master/FAQ/install_KoNLP.md

만약 그래도 오류가 발생하면 데이터 분석 커뮤니티에 올려주세요.

데이터 분석 커뮤니티
https://www.facebook.com/groups/datacommunity/
