### ISSUE TITLE
[교재p73]  "gplot"를 찾을 수  없습니다." 란 에러 메시지가 뜹니다.

### ISSUE THREAD

**Issue by everkook** [youngwoos/Doit_R#38]
안녕하세요. 쉽게 배우는 R 데이터 분석 공부 중입니다.

p71~73 공부 중인데,
ggplot2 패키치 설치 및 로드까지는 성공했으나, 
gplot() 실행이 안됩니다.

설치부터 에러까지의 메시지는 다음과 같습니다.

> install.packages("ggplot2")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/User/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/ggplot2_3.3.0.zip'을 시도합니다
Content type 'application/zip' length 4015332 bytes (3.8 MB)
downloaded 3.8 MB

package ‘ggplot2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\User\AppData\Local\Temp\RtmpOc68tM\downloaded_packages
> library(ggplot2)
> x <- c("a", "a", "b", "c")
> x
[1] "a" "a" "b" "c"
> gplot(x)
**Error in gplot(x) : 함수 "gplot"를 찾을 수 없습니다**
> 

어떻게 해결할 수 있을까요?

**Comment by youngwoos** [comment]
`gplot()`을 `qplot()`으로 수정해서 실행해보시겠어요?

**Comment by everkook** [comment]
감사합니다!!! ^^

2020년 5월 26일 (화) 오전 8:30, Youngwoo Kim <notifications@github.com>님이 작성:
