### ISSUE TITLE
foreign 패키지 설치오류

### ISSUE THREAD

**Issue by gil6301** [youngwoos/Doit_R#39]
안녕하세요

foreign 패키지를 설치하려고 하는데 알 스튜디오 버전때문에 설치가 되지 않습니다. 

Warning in install.packages :
  package ‘foreign’ is not available (for R version 3.6.2)

구글에 찾아봐도 이에대한 정보가 너무 없습니다.
어떻게 해야될까요?

**Comment by youngwoos** [comment]
R 최신 버전을 다운 받아 설치하신 다음 다시 foreign 패키지를 설치해보시겠어요?

**Comment by gil6301** [comment]
안녕하세요! 새로 설치하고나니 정상적으로 실행이 됩니다! 감사합니다~
