### ISSUE TITLE
10-1 텍스트 마이닝 부분 질문입니다

### ISSUE THREAD

**Issue by gil6301** [youngwoos/Doit_R#41]
안녕하세요 

10-1 과에 hiphop 데이터를 준비하는 과정에서 콘솔창에 한글이 깨지는 오류가 계속 생깁니다.

구글에 나와있는 방법으로 최대한 시행해보았으나 한글이 계속 깨져서 나오는데 원인을 알 수가 없네요 ㅜㅜ

![Screen Shot 2020-07-08 at 11 36 42 pm](https://user-images.githubusercontent.com/66740186/86939312-fe4bc600-c173-11ea-9267-26959ccc4a45.png)

도움 주시면 감사하겠습니다.

**Comment by youngwoos** [comment]
아래 글 참고해서 다시 시도해보시겠어요?

**맥에서 불러들인 파일의 문자가 깨질 때**
https://github.com/youngwoos/Doit_R/blob/master/FAQ/Mac_TextEncodingError.md

**Comment by gil6301** [comment]
감사합니다! 완벽하게 인코딩 되었습니다!
