### ISSUE TITLE
오늘 처음 R 공부를 시작했습니다

### ISSUE THREAD

**Issue by song910226** [youngwoos/Doit_R#51]
R 공부한지 3시간 된 (프로그래밍 언어 자체를 공부한지 3시간 됨..) 따끈따끈한 신생아입니다.

Do it! 쉽게 배우는 R 데이터 분석 책으로 공부 시작했습니다.

책에 있는 것을 100% 똑같이 따라하면서 잘 해오는 중에 94쪽에서 안 되네요..

분명 똑같이 썼는데, 계속 "Error in file(file, "rt")  :  cannot open the connection 어쩌구 하면서 에러가 뜹니다.

책에서 설명이 빠진 것은 아닌 것 같은데,
제가 뭘 잘못 설정했나요?

csv 파일 불러오기가 안 됩니다.

csv 파일 저장할 때에도 12쪽에 나온데로 RAW 우클릭 후 다른 이름으로 링크 저장 클릭, 하니 TEXT 파일 같은 것으로 저장 되더군요. 그 뒤로는 d 드라이브에 easy-r 파일 만들어서 저장하고, 엑셀과 csv 파일들도 easy-r에 저장했는데, 엑셀은 인스톨 후 불러오기가 다 되지만, csv파일은 인스톨 할 때부터 약간 다르게 뜹니다. 경로가 윈도우가 깔려있는 c 드라이브에 깔려있다는 콘솔창 description을 봤습니다.

경로가 문제인가 싶어서 c도 쳐보고 d드라이브의 easy_r도 쳐봤는데 둘 다 똑같이 에러가 뜹니다. 책에 있는 대로 해서 안 되어서 다른 것들을 시도해봤는데 안 되요ㅠ 책에는 더 이상의 설명이 없는데ㅠㅠ

**Comment by youngwoos** [comment]
아래 데이터 분석 커뮤니티에 작성한 코드와 화면을 캡쳐해서 올려주시겠어요?

데이터 분석 커뮤니티
https://www.facebook.com/groups/datacommunity/
