### ISSUE TITLE
welfare.csv 파일

### ISSUE THREAD

**Issue by binibin09** [youngwoos/Doit_R#56]
동영상 강의에 나오는 한국복지패널 데이터 csv 파일이 없습니다.
영상에선 'welfare.csv'파일을 공유해주셨다고 하셨는데 못 찾겠어요. ㅜㅜ

**Comment by youngwoos** [comment]
아래 파일 다운로드 하시면 됩니다.
https://github.com/youngwoos/Doit_R/blob/master/Data/csv_exam.csv
