### ISSUE TITLE
dplyr 패키지 관련 오류

### ISSUE THREAD

**Issue by pof1423** [youngwoos/Doit_R#57]
에러: package or namespace load failed for ‘dplyr’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 네임스페이스 ‘ellipsis’ 0.3.1는 이미 로드되었으나 >= 0.3.2가 필요합니다
이런식으로 오류코드가 뜨면서 dplyr 패키지가 실행이 되지 않는데 무엇이 문제인가요? 
백신도 꺼보고/새로 설치도 해보고 패키지 업데이트도 시켜봤는데 계속 저런 오류코드가 뜨고 있습니다.

**Comment by youngwoos** [comment]
`ellipsis` 패키지를 새로 설치한 다음 다시 시도해보시겠어요?  그래도 해결되지 않으면 아래 데이터 분석 커뮤니티에 질문을 올려주세요. 보다 빨리 답변을 받아보실 수 있습니다.

**데이터 분석 커뮤니티**
https://www.facebook.com/groups/datacommunity
