### ISSUE TITLE
교재질문 p212

### ISSUE THREAD

**Issue by vvpreety** [youngwoos/Doit_R#60]
install.packages("foreign")
library(foreign)
library(dplyr)
library(ggplot2)
library(readxl)

raw_welfare <- read.spss(file = "Koweps_hpc10_2015_beta1.sav", to.date.frame=T)
welfare <- raw_welfare

head(welfare)
tail(welfare)
View(welfare)
dim(welfare)
str(welfare)
summary(welfare)

welfare <- rename(welfare, sex = h10_g3, 
                  birth = h10_g4, 
                  marrage = h10_g10, 
                  religion = h10_g11, 
                  income = p1002_8aq1, 
                  code_job = h10_eco9, 
                  code_region = h10_reg7)

여기까지 실행했는데, rename 에서 

Error in UseMethod("rename") : 
  no applicable method for 'rename' applied to an object of class "list"

이라고 떠서 그 뒤에 진행을 못합니다.,
스펠링 틀린것도 없는데 왜 안되는지 알려주실수 없나요..

**Comment by youngwoos** [comment]
`read.spss()`에서 `to.date.frame`을 `to.data.frame`으로 수정해보시겠어요? 그래도 해결되지 않으면 아래 데이터 분석 커뮤니티에 질문을 올려주세요. 보다 빨리 답변을 받아보실 수 있습니다.

데이터 분석 커뮤니티
https://www.facebook.com/groups/datacommunity
