### ISSUE TITLE
scale과 관련한 문제가 있습니다.

### ISSUE THREAD

**Issue by gimbang** [youngwoos/Doit_R#62]
227p, 229p
데이터프레임을 출력해서 보면 문제 없고, 그래프를 바로 출력해도 잘 나오는 것이,
scale_x_discrete를 쓰면 "middle"부분이 없어집니다.
어디서부터 문제가 있는지를 모르겠네요. 책에 나온 오류 메시지를 아무리 봐도 모르겠어서 질문드립니다!
1, 2사진은 오류가 나는 사진이고, 3번째는 데이터프레임은 middle이 0이 아닌 것을 보여드리려고 올렸습니다.

<오류1, 176에 커서를 대고 출력한 결과>
![오류1](https://user-images.githubusercontent.com/94100514/141249108-83d77822-a9b4-4f63-8034-f57ebde85329.PNG)
           
                            
<오류2, 184을 출력함.>
![오류2](https://user-images.githubusercontent.com/94100514/141249118-d6c9c007-a964-40db-86f3-21da7d591621.PNG)
                                        

<181을 출력한 결과 데이터프레임에는 문제가 없음..(제 생각에는요!)>
![income](https://user-images.githubusercontent.com/94100514/141249130-cd0f5c04-a413-4e2d-b223-014556493aa6.PNG)

**Comment by youngwoos** [comment]
`ifelse()`에 `"midde"`라고 입력하셨는데 아마 오타가 아닐까요?

궁금한 사항이 있으시면 아래 데이터 분석 커뮤니티에 질문을 올려주세요.
보다 빨리 답변을 받아보실 수 있습니다.

데이터 분석 커뮤니티
https://www.facebook.com/groups/datacommunity/
