### ISSUE TITLE
교재 p.268 텍스트마이닝 특수문자 제거

### ISSUE THREAD

**Issue by shua0818** [youngwoos/Doit_R#63]
안녕하세요, 텍스트마이닝 예제 연습하다가 문제가 있어서 질문 드립니다.
p.268 에서 txt 파일 불러오기까지 실행하면 한글이 잘 나오는데
> txt <- readLines("hiphop.txt")
> head(txt)
![image](https://user-images.githubusercontent.com/100036910/154808731-38219dbe-9f3d-42a2-b73d-1df70664f281.png)

아래 특수문자 제거 코드를 실행하면 한글이 다 깨져버립니다.
> install.packages("stringr")
> library(stringr)
> txt <- str_replace_all(txt, "\\\W", " ")
![image](https://user-images.githubusercontent.com/100036910/154808844-6a4b4a7d-d5b7-4f87-893c-1fc195290efe.png)

R Studio 인코딩은 UTF-8로 설정해두었구요.
txt 파일 문제인가 싶어 파일 인코딩 바꿔가면서 시도해봤는데 해결되지 않습니다.
무엇이 문제일까요..?ㅠㅠ

**Comment by shua0818** [comment]
해결했습니다!

**Comment by youngwoos** [comment]
해결하셨다니 다행입니다. 어떤 방법으로 해결하셨는지 알려주시겠어요?
